CREATE TABLE customers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       TEXT NOT NULL UNIQUE,
    full_name   TEXT NOT NULL,
    birth_date  DATE,
    loyalty_pts INTEGER
);

CREATE TABLE accounts
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT         NOT NULL REFERENCES customers (id),
    balance  NUMERIC(12, 2) NOT NULL CHECK (balance >= 0)
);
